### ISSUE TITLE
Development branch 

### ISSUE THREAD

**Issue by CvRXX** [kvasir-io/HardwareDescriptionFileGenerator#2]
To make sure people that people know that this project is not usable yet and to keep consistency with the rest of Kvasir it may be good to move the current unfinished version to development.

**Comment by jackieokay** [comment]
Fine with me. Do you prefer "develop" or "development"?

**Comment by jackieokay** [comment]
-pedantic

**Comment by CvRXX** [comment]
I don't really care but in Kvasir register development is used. So let's keep it consistent. 

On 30 November 2016 08:50:38 CET, Jackie Kay <notifications@github.com> wrote:
>Fine with me. Do you prefer "develop" or "development"?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kvasir-io/HardwareDescriptionFileGenerator/issues/2#issuecomment-263806089

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CvRXX** [comment]
No such thing as pedantic when creating a library to change the world 😀.  I will put our git policy online soon. 

On 30 November 2016 08:51:14 CET, Jackie Kay <notifications@github.com> wrote:
>-pedantic
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kvasir-io/HardwareDescriptionFileGenerator/issues/2#issuecomment-263806201

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jackieokay** [comment]
Done, see https://github.com/kvasir-io/HardwareDescriptionFileGenerator/tree/development
